vk:
  secret: ${VK_SECRET:<secret>}
  confirmation-code: ${VK_CONFIRMATION_CODE:123456}
  api:
    version: 5.131
    token: ${VK_API_TOKEN}
quarkus:
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  datasource:
    db-kind: postgresql

  rest-client:
    scope: jakarta.inject.Singleton
    logging:
      scope: request-response
    vk:
      url: https://api.vk.ru/method
      headers:
        Authorization: Bearer ${vk.api.token}
  rabbitmq:
    devservices:
      image-name: rabbitmq:latest

mp:
  messaging:
    incoming:
      all-events-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
        queue:
          name: queue
    outgoing:
      events-exchange:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
