vk:
  secret: <secret>
  confirmation-code: 123456
  api:
    version: 5.131
    token: REQUIRED_TO_BE_REPLACED
quarkus:
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  datasource:
    db-kind: postgresql

  rest-client:
    scope: jakarta.inject.Singleton
    logging:
      scope: request-response
    vk:
      url: https://api.vk.ru/method
      headers:
        Authorization: Bearer ${vk.api.token}
#  smallrye-reactive-messaging:
#    events:
#      connector: rabbitmq
#      exchange-name: events-exchange
#      queue-name: events-queue
#      routing-key: '#'


  rabbitmq:
    devservices:
      image-name: rabbitmq:latest

mp:
  messaging:
    incoming:
      all-events-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
        queue:
          name: queue
    outgoing:
      events-exchange:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
