vk:
  secret: ${VK_SECRET}
  confirmation-code: ${VK_CONFIRMATION_CODE}
  api:
    version: 5.199
    token: ${VK_API_TOKEN}
quarkus:
  config:
    locations: application-queues.yml
  application:
    name: vk-bot
  hibernate-orm:
    schema-management:
      strategy: validate
  datasource:
    db-kind: postgresql
    devservices:
      enabled: true
  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml
  otel:
    logs:
      enabled: true
      level: INFO
    metrics:
      enabled: true
    traces:
      enabled: true
  rest-client:
    scope: jakarta.inject.Singleton
    logging:
      scope: request-response
    vk:
      url: https://api.vk.ru/method
      headers:
        Authorization: Bearer ${vk.api.token}
  rabbitmq:
    devservices:
      image-name: rabbitmq:latest
  langchain4j:
    log-requests: true
    log-responses: true
    tracing:
      include-prompt: true
      include-completion: true

mp:
  messaging:
    incoming:
      all-events-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
        queue:
          name: queue
        dead-letter-exchange: retry-5s-exchange
      retry-5s-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-5s-exchange
        queue:
          name: retry-5s
          arguments:
            x-message-ttl: 5000
            x-dead-letter-exchange: all-events
            x-dead-letter-routing-key: queue
      retry-30s-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-30s-exchange
        queue:
          name: retry-30s
          arguments:
            x-message-ttl: 30000
            x-dead-letter-exchange: all-events
            x-dead-letter-routing-key: queue
      retry-1m-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-1m-exchange
        queue:
          name: retry-1m
          arguments:
            x-message-ttl: 60000
            x-dead-letter-exchange: all-events
            x-dead-letter-routing-key: queue
      retry-15m-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-15m-exchange
        queue:
          name: retry-15m
          arguments:
            x-message-ttl: 900000
            x-dead-letter-exchange: all-events
            x-dead-letter-routing-key: queue
      retry-1h-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-1h-exchange
        queue:
          name: retry-1h
          arguments:
            x-message-ttl: 3600000
            x-dead-letter-exchange: all-events
            x-dead-letter-routing-key: queue
      dlq-final-queue:
        connector: smallrye-rabbitmq
        exchange:
          name: dlq-final-exchange
        queue:
          name: dlq-final
    outgoing:
      events-exchange:
        connector: smallrye-rabbitmq
        exchange:
          name: all-events
      retry-5s-out:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-5s-exchange
      retry-30s-out:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-30s-exchange
      retry-1m-out:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-1m-exchange
      retry-15m-out:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-15m-exchange
      retry-1h-out:
        connector: smallrye-rabbitmq
        exchange:
          name: retry-1h-exchange
      dlq-final-out:
        connector: smallrye-rabbitmq
        exchange:
          name: dlq-final-exchange

smallrye:
  messaging:
    observation:
      enabled: true
